version: "3.9"

networks:
  default:
    name: hello-rails-postgres-redis_default

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myapp_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - default

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://myuser:mypassword@postgres:5432/myapp_development?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - default

  redis_exporter:
    image: oliver006/redis_exporter:v1.47.0
    command:
      - --redis.addr=redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - default

  rails_app:
    build: ./app
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/myapp_development"
      REDIS_URL: "redis://redis:6379/0"
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - default

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - postgres_exporter
      - redis_exporter
      - rails_app
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - default

volumes:
  pgdata:
