groups:
- name: app-alerts
  rules:
  - alert: HighErrorRate
    expr: increase(rails_request_errors_total[5m]) > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High error rate on Rails app"

- name: postgres-alerts
  rules:
  - alert: PostgresTooManyConnections
    expr: pg_stat_activity_count > 90
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Too many connections to Postgres"

- name: redis-alerts
  rules:
  - alert: RedisMemoryUsageHigh
    expr: redis_memory_used_bytes / redis_memory_total_bytes > 0.8
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Redis memory usage above 80%"
